# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md

name: Tony
fileGroups: []
configs:
  Debug: debug
  Release: release
options:
  minimumXcodeGenVersion: "2.25.0"
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    iOS: "14.0"
  developmentLanguage: ja
attributes:
  ORGANIZATIONNAME: "yuoku"
settingGroups:
  applicationSetting:
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: B8PR34D6DP
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_FILE: App/Tony/Sources/Resources/Info.plist
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
    INFOPLIST_KEY_UIMainStoryboardFile: Main
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    IPHONEOS_DEPLOYMENT_TARGET: 14.0
    LD_RUNPATH_SEARCH_PATHS: $(inherited), @executable_path/Frameworks
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    PRODUCT_BUNDLE_IDENTIFIER: jp.yuoku.Tony
    PRODUCT_NAME: "$(TARGET_NAME)"
    SWIFT_EMIT_LOC_STRINGS: YES
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: "1,2"
include:
  - path: XcodeGen/TonyCore.yml
    relativePaths: false
  - path: XcodeGen/SandboxCore.yml
    relativePaths: false
  - path: XcodeGen/SplashFeatures.yml
    relativePaths: false
  - path: XcodeGen/SearchRepoFeatures.yml
    relativePaths: false

targets:
  Tony:
    type: application
    platform: iOS
    settings:
      groups: [applicationSetting]
    sources:
      - path: App/Tony
        excludes:
          - "**/.gitkeep"
          - "**/*.md"
    dependencies:
      - target: TonyCore
      - target: SplashFeatures
      - target: SearchRepoFeatures
    postCompileScripts:
      - path: ./Scripts/swift-format.sh
        name: swift-format

  TonyTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
      BUNDLE_NAME: 'application.Tony.tests'
      configs:
        Debug:
          VALIDATE_WORKSPACE: YES
    sources:
      - App/TonyTests
    dependencies:
      - target: Tony

  TonyUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
      BUNDLE_NAME: 'application.Tony.uitests'
      configs:
        Debug:
          VALIDATE_WORKSPACE: YES
    sources:
      - App/TonyUITests
    dependencies:
      - target: Tony

schemeTemplates:
  TonyScheme:
    build:
      targets:
        Tony: all
        TonyTests: [test]
        TonyUITests: [test]
    run:
      config: ${debugConfig}
    test:
      config: ${debugConfig}
      targets:
        - TonyTests
        - TonyUITests
    profile:
      config: ${releaseConfig}
    analyze:
      config: ${debugConfig}
    archive:
      config: ${releaseConfig}
schemes:
  Tony:
    templates: [TonyScheme]
    templateAttributes:
      debugConfig: Debug
      releaseConfig: Release
